### ISSUE TITLE
port to SBT 1.*

### ISSUE THREAD

**Issue by yuxh** [high-performance-spark/high-performance-spark-examples#97]
it's difficult to work in intellij with sbt 0.13(it's a long time to "dump project structure from sbt"). plugin like sbt-spark-package seems not work in sbt 1.* .

**Comment by jiminhsieh** [comment]
If you are using `0.13.18`, IntelliJ should able to work with.

**Comment by holdenk** [comment]
We've upgraded! Sorry it took so long.
